### ISSUE TITLE
PALERMO - Campaña noche de Tango

### ISSUE THREAD

**Issue by gaby-troiatec** [Neuronsinc/Coordinacion-de-cuentas#11]
Hola Andrés. 

Hay una nueva campaña en Palermo para reservas que se debe subir. 

En tu campaña de Mensajes ya creada debes crear un nuevo conjunto de anuncios con el nombre de este arte. 
Fecha inicio: 08 noviembre
Fecha fin: 24 noviembre 17 hrs. 
Abajo de la fecha hay una casilla que dice "Límites de gasto del conjunto de anuncios" al seleccionarla debes colocarle Mínimo Total Q400
Esto es para que de tu presupuesto total en la campaña la plataforma mínimo le asigne Q400 solo a este conjunto. 

En cuanto al público puedes utilizar tu experiencia con segmentación pero te sugiero geolocalizarla por zonas: 9, 10, 11, 13, 14, 15, 16, carretera a el salvador, santa catarina pinula, fraijanes. Porque si la dejaras a nivel ciudad guatemala entran mensajes de zonas que solo curiosean y no son el público. 
Con intereses puedes hacerla de dos formas, una es solo perfilativa como la que ya tienes que es solo por zonas e intereses o bien mi recomendación es que uses las audiencias para llegar más a un público que sabes han interactuado con Palermo. Para ello yo haría un retargeting de personas que interactuaron con palermo en los últimos 120 días siempre con publico similar, y aparte usar los bolsones de audiencias de lead enforce LI Comida tenedor, LE Restaurantes premium, base de datos clientes palermo. No colocaría intereses adicionales porque ya estás siendo bien específico con la audiencia. 

**Copy:** Vení con tu pareja a la noche de tango en Palermo, junto a Emy Cobian, su voz inigualable y bailarines de Tango. Ademas en la compra de nuestros vinos escogidos, unas boquitas excepcionales que nuestro chef Ariel preparó para que esta velada sea única. 
Precio por pareja: Q399
Los esperamos este 24 de noviembre a las 19:00 hrs en Palermo Spazio, z.15. 

Título: 
- Reservá por mensaje
- Vení a Palermo Spazio 

Artes: https://drive.google.com/drive/folders/1PuzDLD1pQCq8gYkUqbCWhS06Ocn9ZU6R
Son 2 post y 2 historias. Vamos a medir a cual le va mejor. 

Cualquier duda nos cuentas, gracias.

**Comment by gaby-troiatec** [comment]
@Marlyn-mejia17

**Comment by Andres040523** [comment]
Buenos días @gaby-troiatec @Marlyn-mejia17 en unos momentos quedará lista la nueva campaña de Palermo y les aviso por este medio que ya esta finalizada.
