### ISSUE TITLE
LARES 17 - Cambio cuota en artes y copys

### ISSUE THREAD

**Issue by gaby-troiatec** [Neuronsinc/Coordinacion-de-cuentas#12]
Hola Andrés. 

Solicito tu apoyo para hacer el cambio de anuncios en las campañas de Lares 17. Tanto en la abierta como en la que tiene límite de puja. 

Adjunto los artes para sustituir todos los activos en Lares 17: https://www.dropbox.com/scl/fo/cq1dx5gen4kk26amgbiuv/h?rlkey=wgce1av7cqu6ywm79x2we9opp&dl=0

Favor tomar en cuenta que en el excel se cambio imágenes y copys y algunos títulos que van marcados en amarillo.
Lo artes marcados en azul, no tiene cuota en arte por tal razón no cambian más que solo en el copy, pero igual le adjunte los artes nuevamente.

Favor tomar en cuenta que el modelo C de 65 m2 debemos de eliminarlo de la pauta, por eso no va incluido en el excel. 

Cualquier duda me cuentas.

**Comment by gaby-troiatec** [comment]
@Marlyn-mejia17

**Comment by Andres040523** [comment]
Hola @Marlyn-mejia17 doy por terminada la tarea.
