### ISSUE TITLE
Campaña Nikao - nuevas audiencias

### ISSUE THREAD

**Issue by gaby-troiatec** [Neuronsinc/Coordinacion-de-cuentas#9]
Hola Andrés.

Hay que crear una nueva campaña para Nikao con los Q10,000 pendientes a implementar. 

Objetivo: Clientes potenciales
Audiencias:

1. Lead Intelligence: usar audiencias apartamentos premium LI + aptos medio LI. Colocar intereses de apartamentos. 
2. Retargeting: personas que interactuaron con Nikao en los últimos 120 días, + publico similar al 1% de estas personas, tanto en facebook como en instagram. Excluir a los que ya enviaron el formulario. Como lo que se hizo con CMI. Colocar intereses y comportamientos de inmobiliaria. 

Gracias.

**Comment by gaby-troiatec** [comment]
@PabloLeal17

**Comment by Andres040523** [comment]
Hola @gaby-troiatec ahora lo comienzo a realizar

**Comment by Andres040523** [comment]
Hola @gaby-troiatec @PabloLeal17 ya están publicadas y corriendo las campañas. Quedo pendiente a cualquier cosa.
